# Generated by Django 3.2.6 on 2021-10-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalyear',
            name='planting_type',
            field=models.CharField(choices=[('harvest', 'Safra'), ('off-season', 'Safrinha')], default=('harvest', 'Safra'), max_length=20),
        ),
        migrations.AlterField(
            model_name='plot',
            name='first_or_second_planting',
            field=models.IntegerField(choices=[(1, 'Primeiro'), (2, 'Segundo')]),
        ),
    ]
