# Generated by Django 3.2.6 on 2021-10-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211024_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='identifier',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
