# Generated by Django 3.2.6 on 2021-10-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plot_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilanalysis',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
