# Generated by Django 3.2.6 on 2021-10-30 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_soilanalysis_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicallabreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chemicallabreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physicallabreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='soil_class',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='iqs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='npk',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
