# Generated by Django 3.2.6 on 2021-10-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211030_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalyear',
            name='planting_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
