# Generated by Django 3.2.6 on 2021-10-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_agriculturalyear_planting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicallabreport',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grid'),
        ),
        migrations.AddField(
            model_name='chemicallabreport',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grid'),
        ),
        migrations.AddField(
            model_name='physicallabreport',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grid'),
        ),
    ]
