# Generated by Django 3.2.6 on 2021-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211031_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='identifier',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
