# Generated by Django 3.2.6 on 2021-11-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_grid_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agriculturalyear',
            name='plot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plot'),
        ),
    ]
