# Generated by Django 3.2.6 on 2021-11-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211103_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='mineral_fertilizer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
