# Generated by Django 3.2.6 on 2021-11-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_recommendation_mineral_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='agricultural_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.agriculturalyear'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agriculturalyear',
            name='planting_type',
            field=models.CharField(choices=[('harvest_20_21', 'Safra 20/21'), ('off-season_20_21', 'Safrinha 20/21'), ('harvest_21_22', 'Safra 21/22'), ('off-season_21_22', 'Safrinha 21/22'), ('harvest_22_23', 'Safra 22/23'), ('off-season_22_23', 'Safrinha 22/23'), ('harvest_24_25', 'Safra 24/25'), ('off-season_24_25', 'Safrinha 24/25')], default=('harvest_20_21', 'Safra 20/21'), max_length=20),
        ),
    ]
