# Generated by Django 3.2.6 on 2021-11-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_plot_agricultural_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='agricultural_year',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
